project_id = "yinicwvgwdjlkwjegrun"

[functions.parse-search-query]
verify_jwt = false

[functions.generate-test-contacts]
verify_jwt = true

[functions.scan-business-card]
verify_jwt = true

[functions.slack-integration]
verify_jwt = false

[functions.teams-integration]
verify_jwt = false

[functions.parse-contact-input]
verify_jwt = true

[functions.parse-contact-pdf]
verify_jwt = true

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
