// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createSupabaseStub(message: string) {
  return new Proxy(
    {},
    {
      get() {
        throw new Error(message);
      },
    },
  ) as any;
}

export const supabase = (() => {
  const missingMsg =
    "Supabase configuration missing. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set at build time.";

  if (!isSupabaseConfigured) {
    // Avoid crashing the whole app bundle (shows as a blank white screen in production).
    console.error(`[Supabase] ${missingMsg}`);
    return createSupabaseStub(missingMsg);
  }

  try {
    return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (e) {
    console.error("[Supabase] Failed to initialize client:", e);
    return createSupabaseStub(
      "Supabase initialization failed. Check build-time env vars and runtime storage availability.",
    );
  }
})();